version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: control_asistencia_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - '3000:3000'
